name: railsafe_spad_poc
description: RailSafe SPAD Prevention Mobile App - A POC that uses camera and ML to detect railway signals and alert drivers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Camera functionality
  camera: ^0.10.5+5

  # Machine learning (disabled for initial build)
  # tflite_flutter: ^0.10.4
  image: ^4.1.3

  # UI and navigation
  cupertino_icons: ^1.0.2

  # Audio alerts
  audioplayers: ^5.2.1

  # Utilities
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/